worker_processes 1;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    server {
        listen      NGINX_PORT;
        root        /var/www/html;
        index       index.php index.html;

        access_log  /dev/stdout;
        error_log   /dev/stderr warn;

        location ~ ^/(\.env|\.git|\.htaccess)$ {
            deny all;
            return 404;
        }
        location ~ ^/api/helpers\.php$ {
            deny all;
            return 404;
        }

        location ~ \.php$ {
            try_files      $uri =404;
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include        fastcgi_params;
        }

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
